### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/qgis-loopplugin#1]
When installing using the "Finally, you can add the folowing path to the list of Plugin Repositories in the QGIS Settings: https://raw.githubusercontent.com/Loop3D/qgis-loopplugin/master/plugins.xml" option I get the following error

Plugin has disappeared: The plugin seems to have been installed but it's not possible to know where. The directory "C:/Users/lachl/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins/master" has not been found. Probably the plugin package contained a wrong named directory. Please search the list of installed plugins. You should find the plugin there, but it's not possible to determine which of them it is and it's also not possible to inform you about available updates. Please contact the plugin author and submit this issue.

The plugin appears in the plugin browser as Loop processor 
![image](https://user-images.githubusercontent.com/7371904/199620782-98d039ee-1030-490f-8c30-cdb99b3dd20b.png)

but it cannot be enabled.

**Comment by markjessell** [comment]
I have removed the instructions in the readme until I figure this out!

**Comment by ice-jing** [comment]
无法加载插件“qgis-loopplugin-main”因在调用其classFactory()方法时发生错误 
Check the new release and read what required before installing the package into qgis.

**Comment by ShebMichel** [comment]
ice-jing

**Comment by ShebMichel** [comment]
Check the new release and read what required before installing the package into qgis.
