### ISSUE TITLE
Capitals in module names cause errors for me

### ISSUE THREAD

**Issue by GeoMattB** [Loop3D/qgis-loopplugin#14]
The lep_function and load_vectors functions / modules are refernenced using lower case in the code but named using upper case.
![image](https://user-images.githubusercontent.com/29564171/203176232-07978bba-b6d3-41e6-becf-6ba1bf43a6b6.png)

**Comment by ShebMichel** [comment]
Thanks GeoMattB, format have been fixed and repo is updated.

**Comment by ShebMichel** [comment]
Issue closed
