### ISSUE TITLE
Can you publish your example data?

### ISSUE THREAD

**Issue by ice-jing** [Loop3D/qgis-loopplugin#17]

**Comment by ShebMichel** [comment]
Share your data and tell me what you want to achieve, I might be helpful. cheers!

**Comment by ice-jing** [comment]
I'd like to learn how this plugin is applied based on your case study, as I'm currently in the learning phase and don't really understand how this plugin relates to loopstructure. @ShebMichel

**Comment by ShebMichel** [comment]
At the moment, we are running map2loop from within the plugin. In future releases, loopstructural signal will be activated to the plugin. This means, you will be able to build 3D model from the output of loopstructural. The output of map2loop you get from the plugin is used as an input for loopstructural modelling.
