### ISSUE TITLE
question

### ISSUE THREAD

**Issue by ice-jing** [Loop3D/qgis-loopplugin#18]
![X_D%EX8VC 7ICCIB)SFKH8X](https://github.com/Loop3D/qgis-loopplugin/assets/117960349/5c1ecd77-11a6-456a-bebf-cf1b3602e0d4)

How to import the output data into loopstructure and generate a 3D model?

**Comment by ShebMichel** [comment]
If are using the last version of the plugin, you will see a "Run LoopStructural" pushbutton. This feature will be connected in the next release. However, if you can run map2loop successfully, you will have to use its output to run LoopStructural manually to generate 3D model. Check on the github repo for example on how to run LoopStructural. Cheers!

**Comment by markjessell** [comment]
The Run_test.py is a script that runs the map2loop code, and you can paste in, after proj.run(), the code from the map2loop notebook :

https://github.com/Loop3D/map2loop2-notebooks/blob/master/Example%201%20-%20Using%20Loop's%20Sources.ipynb

(just the cells below the Loop Structural title)

cheers
mark

From: ice-jing ***@***.***>
Sent: Wednesday, 22 November 2023 11:41 AM
To: Loop3D/qgis-loopplugin ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Loop3D/qgis-loopplugin] question (Issue #18)


[X_D%EX8VC 7ICCIB)SFKH8X]<https://user-images.githubusercontent.com/117960349/284783271-5c1ecd77-11a6-456a-bebf-cf1b3602e0d4.png>

How to import the output data into loopstructure and generate a 3D model?

-
