### ISSUE TITLE
Loading layer from qgis layers

### ISSUE THREAD

**Issue by lachlangrose** [Loop3D/qgis-loopplugin#3]
Is is possible to load a layer from the qgis layers panel rather than loading an external file?

This should have been close long ago

**Comment by ozguryedek** [comment]
The layers on the Structures section (bedding data) are not listed on the drop-down menu from QGIS layers.
Can you add a screen capture of the issue here?

**Comment by ozguryedek** [comment]
> 
![Screenshot 2023-05-06 211931](https://user-images.githubusercontent.com/82779752/236627095-04beaed7-a1d0-458a-8134-4036a36ec605.png)

 The geology and fault sections are working very well but the structure section. The bedding layer (point data) is not listed when Qgis is checked. The external file is available only.

**Comment by ShebMichel** [comment]
@ozguryedek, can you send me directly the structure file, I think I may have an idea of what is going on?

**Comment by ShebMichel** [comment]
@ozguryedek please clone the repo and test it again? It should be working now. let me know so that I can close this issues. Thanks

**Comment by ozguryedek** [comment]
I have tested and now the data is listed. Thanks.

**Comment by ShebMichel** [comment]
Issues solved and closed.!
